jenkins:
  systemMessage: "\n\nDemo setup for Jenkins Configuration as Code plugin......\n\n"

  numExecutors: 2
  mode: NORMAL
  scmCheckoutRetryCount: 3
  labelString: "master-label"  

  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: dfdjugfdg

  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:anonymous"
        - "Job/Read:anonymous"
        - "View/Read:anonymous"
        - "Overall/Administer:anonymous"

  crumbIssuer: "standard"

  remotingSecurity:
    enabled: true    

credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
            scope:    GLOBAL
            id:       github-user
            username: Marevo
            password: "{{gitpass}}" 
            description: github username/password  

tool:
  git:
    installations:
      - name: Default
        home: "git"


